import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class CustomerStatistics
{
	public String[] reportDuplicates(String[] customerNames)
	{
		HashMap<String,Integer> map = new HashMap<String,Integer>();
		for(int i = 0 ; i < customerNames.length ; i++){
			if(map.containsKey(customerNames[i])){
				map.replace(customerNames[i],map.get(customerNames[i])+1);
			}
			else{
				map.put(customerNames[i],1);
			}				
		}
		ArrayList<String> list = new ArrayList<String>();
		for (Map.Entry<String,Integer> entry : map.entrySet()) {
		    String key = entry.getKey();
		    Integer value = entry.getValue();
		    if(value>1){
		    	list.add(key+" "+value);
		    }
		}
		Collections.sort(list);
		String str [];
		str = list.toArray(new String[list.size()]);
		return str;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String[] p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		CustomerStatistics obj;
		String[] answer;
		obj = new CustomerStatistics();
		long startTime = System.currentTimeMillis();
		answer = obj.reportDuplicates(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p1.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print("\"" + p1[i] + "\"");
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + answer[i] + "\"");
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p1.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (!answer[i].equals(p1[i])) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String[] p1;
		
		// ----- test 0 -----
		p0 = new String[]{"JOHN","BOB","JOHN","BILL","STANLEY","JOHN"};
		p1 = new String[]{"JOHN 3"};
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"YETTI","YETTI","YETTI","BIGFOOT","BIGFOOT"};
		p1 = new String[]{"BIGFOOT 2","YETTI 3"};
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"ANDREW","BILL","CINDY","DOH","ERGH","FOO","GOO","HMPH"};
		p1 = new String[]{};
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"THEONLYCUSTOMER"};
		p1 = new String[]{};
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"A","B","A","C","A","B","A","D","D","D"};
		p1 = new String[]{"A 4","B 2","D 3"};
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
