import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class ObjectFall
{
	public int howLong(int x, int y, String[] obstacles)
	{
		int totalsec=y;
		List<String> list =  Arrays.asList(obstacles);
		Collections.sort(list);
		Collections.reverse(list);
		for(int i = 0 ; i < obstacles.length ; i++){
			Integer yref = Integer.parseInt(obstacles[i].substring(0,3));
			Integer xleft = Integer.parseInt(obstacles[i].substring(4,7));
			Integer xright = Integer.parseInt(obstacles[i].substring(8,11));
			if(y>yref){
				y--;
				i--;
			}
			else if(y==yref){
				if(x>=xleft && x <=xright){
					totalsec+=5;
					x=xright;
					y--;
				}
				else{
					y--;
				}
			}
			else{
				int j;
				for(j = i+1 ; j < obstacles.length ; j++){
					Integer yref1 = Integer.parseInt(obstacles[j].substring(0,3));
					if(yref1<=y)
						break;
				}
				if(j==obstacles.length)
					break;
				else{
					i=j-1;
				}
			}
			
		}
		
		return totalsec;
	}
	/*
	 * 
	 * if(i<obstacles.length){
				Integer yref = Integer.parseInt(obstacles[i].substring(0,3));
				Integer xleft = Integer.parseInt(obstacles[i].substring(4,7));
				Integer xright = Integer.parseInt(obstacles[i].substring(8,11));
				if(y==yref && x >=xleft && x<=xright){
					totalsec+=5;
					x=xright;
					i++;
				}
				else if(y==yref){
					i++;
				}
				else if(y > yref){
					
				}
				else{
					
				}
			}
	 */
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, String[] p2, boolean hasAnswer, int p3) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + "{");
		for (int i = 0; p2.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p2[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		ObjectFall obj;
		int answer;
		obj = new ObjectFall();
		long startTime = System.currentTimeMillis();
		answer = obj.howLong(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p3);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p3;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		int p1;
		String[] p2;
		int p3;
		
		// ----- test 0 -----
		p0 = 15;
		p1 = 10;
		p2 = new String[]{"005 010 020"};
		p3 = 15;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 15;
		p1 = 12;
		p2 = new String[]{"010 010 020","015 010 020","005 020 050"};
		p3 = 22;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 50;
		p1 = 85;
		p2 = new String[]{"020 001 100","010 100 100","005 100 200"};
		p3 = 100;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 10;
		p1 = 1000;
		p2 = new String[]{};
		p3 = 1000;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = 500;
		p1 = 800;
		p2 = new String[]{"800 001 500","400 001 499","401 501 999"};
		p3 = 805;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = 645;
		p1 = 802;
		p2 = new String[]{"739 038 799","916 169 791","822 372 911","162 125 992","261 307 545","510 031 765","592 723 742","477 315 676","566 143 617","337 114 664","986 648 883","116 230 680","254 746 943","742 948 988","060 117 401","634 035 433","288 741 864","819 626 730","906 071 222","554 100 121","573 051 551","949 528 915","562 151 223","857 135 243","621 115 474","588 405 615","895 812 919","052 378 836","858 116 505","285 428 469","792 244 250","109 265 637","714 804 885","625 150 410","518 593 921","282 235 339","081 212 659","663 047 982","556 194 345","798 150 938","391 026 813","886 348 796","975 007 743","053 854 895","243 561 875"};
		p3 = 817;
		all_right = KawigiEdit_RunTest(5, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
