import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class PaperRockScisQuals
{
	public int whoPassed(String[] players)
	{
		 double scores[] = new double[players.length];
		 for(int i = 0 ;i < players.length ; i++){
			 for(int j = i+1 ; j< players.length ; j++){
				 int result = whoWon(i,j,players[i],players[j]);
				 if(result==-1){
					 scores[i]+=0.5;
					 scores[j]+=0.5;
				 } 
				 else{
					 scores[result]+=1;
				 }
			 }
		 }
		 
		 int index = 0;
		 for(int i = 1 ; i<players.length ;i++){
			 if(scores[i] > scores[index])
				 index=i;
		 }
		 return index;
	}
	
	public int whoWon(int index1,int index2,String streak1, String streak2){
		int point1,point2;
		point1=point2=0;
		for(int i = 0 ; i < streak1.length() ; i++){
			if(streak1.charAt(i)!=streak2.charAt(i)){
				char a = streak1.charAt(i);
				char b = streak2.charAt(i);
				if(a=='P' && b=='R'){
					point1++;
				}
				else if(a=='R' && b=='P'){
					point2++;
				}
				else if(a=='P' && b=='S'){
					point2++;
				}
				else if(a=='S' && b=='P'){
					point1++;
				}
				else if(a=='R' && b=='S'){
					point1++;
				}
				else{
					point2++;
				}
			}
		}
		if(point1==point2)
			return -1;
		else if(point1 > point2)
			return index1;
		else 
			return index2;
	}
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, int p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		PaperRockScisQuals obj;
		int answer;
		obj = new PaperRockScisQuals();
		long startTime = System.currentTimeMillis();
		answer = obj.whoPassed(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p1);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		int p1;
		
		// ----- test 0 -----
		p0 = new String[]{"PPRRS","PPRRP","PPRSP","PPSSP"};
		p1 = 0;
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"RRRRR","PPPPP","RRRRR","PPPPP"};
		p1 = 1;
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"RRRRR","PPPPP","SSSSS","PPPPP"};
		p1 = 2;
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"RRRRR","PPPPP","SSSSS","SSSSS","RRRRR","RRRRR"};
		p1 = 0;
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"PPRPS","RRRPR","SSPRS","SSPRR","PPRSP","SPRPS","SPRSP","PRSPR","PRSPR"};
		p1 = 6;
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
