import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class RectangleGroups
{
	int sum[] = new int[26];
	
	public String maximalIndexed(String[] rectangles)
	{
		for(int i = 0 ; i < rectangles.length ; i++){
			String temp[] = rectangles[i].split(" ");
			sum[temp[0].charAt(0)-'A']+=(Integer.parseInt(temp[1])*Integer.parseInt(temp[2]));
		}
		int index=-1,max=0;
		for(int i = 0 ; i <26 ; i++){
			if(sum[i]>max){
				max=sum[i];
				index=i;
			}
		}
		char x = (char)('A'+index);
		return x+" "+max;
	}
	
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		RectangleGroups obj;
		String answer;
		obj = new RectangleGroups();
		long startTime = System.currentTimeMillis();
		answer = obj.maximalIndexed(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p1 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p1);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String p1;
		
		// ----- test 0 -----
		p0 = new String[]{"A 1 2","A 3 3"};
		p1 = "A 11";
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"A 1 2","B 3 3","A 2 1"};
		p1 = "B 9";
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"D 1 6","F 2 3","G 1 1","G 5 1","C 3 2"};
		p1 = "C 6";
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"S 2 54","Y 34 65","F 234 23","D 84 127","R 603 46","S 36 192","Y 76 32","T 54 28","S 22 22"};
		p1 = "R 27738";
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
