import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class SandwichBar
{
	public int whichOrder(String[] available, String[] orders)
	{
		HashSet<String> set = new HashSet<String>();
		for(int i = 0 ; i < available.length ; i++){
			set.add(available[i]);
		}
		for(int i = 0 ; i<orders.length ; i++){
			String temp[] = orders[i].split(" ");
			int j;
			for(j = 0 ; j<temp.length ; j++){
				if(!set.contains(temp[j]))
					break;
			}
			if(j==temp.length)
				return i;
		}
		return -1;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, String[] p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p1[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		SandwichBar obj;
		int answer;
		obj = new SandwichBar();
		long startTime = System.currentTimeMillis();
		answer = obj.whichOrder(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String[] p1;
		int p2;
		
		// ----- test 0 -----
		p0 = new String[]{"ham","cheese","mustard"};
		p1 = new String[]{"ham cheese"};
		p2 = 0;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"cheese","mustard","lettuce"};
		p1 = new String[]{"cheese ham","cheese mustard lettuce","ketchup","beer"};
		p2 = 1;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"cheese","cheese","cheese","tomato"};
		p1 = new String[]{"ham ham ham","water","pork","bread","cheese tomato cheese","beef"};
		p2 = 4;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"foo","bar","baz","gazonk","quux","bat","xyzzy","shme","hukarz","grault","waldo","bleh"};
		p1 = new String[]{"kalatehas","spam eggs","needle haystack","bleh blarg","plugh","the best sandwich in the universe"};
		p2 = -1;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
