import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class TaxTable
{
	public int income(int taxAmount)
	{
		double lim1 = (100000*25*1.0)/100 - 6525;
		double lim2 = (117249*25*1.0)/100 - 6525;
		double lim3 = (117250*28*1.0)/100 - 10042.50;
		double lim4 = (178649*28*1.0)/100 - 10042.50;
		double lim5 = (178650*33*1.0)/100 - 18975.00;
		double lim6 = (319099*33*1.0)/100 - 18975.00;
		double lim7 = (319100*35*1.0)/100 - 25357.00;
		if(taxAmount<lim1)
			return -1;
		else if(taxAmount>=lim1 && taxAmount<=lim2){
			double temp = ((taxAmount+6525)*100)/(1.0*25);
			return (int)Math.round(temp);
		}
		else if(taxAmount>=lim3 && taxAmount<=lim4){
			double temp = ((taxAmount+10042.50)*100)/(1.0*28);
			return (int)Math.round(temp);			
		}
		else if(taxAmount>=lim5 && taxAmount<=lim6){
			double temp = ((taxAmount+18975.00)*100)/(1.0*33);
			return (int)Math.round(temp);			
		}
		else{
			double temp = ((taxAmount+25357.00)*100)/(1.0*35);
			return (int)Math.round(temp);			
		}
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, boolean hasAnswer, int p1) {
		System.out.print("Test " + testNum + ": [" + p0);
		System.out.println("]");
		TaxTable obj;
		int answer;
		obj = new TaxTable();
		long startTime = System.currentTimeMillis();
		answer = obj.income(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p1);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		int p1;
		
		// ----- test 0 -----
		p0 = 47025;
		p1 = 200000;
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 1000;
		p1 = -1;
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 47026;
		p1 = 200003;
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 86304;
		p1 = 319027;
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = 22792;
		p1 = 117266;
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
